### ISSUE TITLE
License should permit forking but disallow reuse of the name

### ISSUE THREAD

**Issue by amyjko** [reciprocalreviews/reciprocalapp#3]
If someone forks this repository, they should not be allowed to reuse the name, as it would cause confusion about the purpose, scope, and nature of the effort.

**Comment by amyjko** [comment]
@utmandrew We need to account for this in our license. We have a placeholder MIT license right now ([LICENSE](https://github.com/reciprocalreviews/reciprocalapp/blob/main/LICENSE), so that's where the draft license text should go.

**Comment by utmandrew** [comment]
Proposal: let's consider the [Mozilla Public License (version 2)](https://www.mozilla.org/en-US/MPL/2.0/).  

It is more restrictive than MIT. It is copyleft but still allows for the work to be incorporated in a larger, differently licensed piece of work so long as this component remains open and available.  There is already a carve out for trademarks; I'd need to look into when a name might be considered a trademark (unregistered).

**Comment by amyjko** [comment]
That might be a good option. Copyleft seems reasonable in this case given our goals of transparency and trust.

**Comment by utmandrew** [comment]
I did a bit more reading, and I am a bit put off by the file-level tracking that the MPL 2.0 requires. Typically, each file has a header indicating that it is MPL 2.0, and this allows subsequent authors to blend this source code with their own.

That led me to the Eclipse Public License (EPL). It's another weak copyleft. If someone built a product that *modifies* this code, the source code would need to be released, but if their product merely uses this code (building around it), then the source code would not need to be released. It also protects trademark, which I think is this fundamental requirement.

**Comment by utmandrew** [comment]
Also, we should indicate that ReciprocalReviews is a trademark by marking it as such "(TM)" -- any concerns there?

**Comment by amyjko** [comment]
EPL seems interesting and viable. (Also, we wouldn't need to use the word "Eclipse" — we can write our own license with similar language).

And yes to trademarking. It's a good nudge to prevent people from reclaiming the name and warping the brand.

**Comment by utmandrew** [comment]
Happy to make the changes to various files if MPL is acceptable and the group wants to do per-file attribution.

**Comment by amyjko** [comment]
Yes, go ahead and make changes to files. I think tracking our work publicly and documenting our decisions here is a good idea.

**Comment by utmandrew** [comment]
For reference, the headers added are, for ts/js style files:

`/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */`
 
 And for html/svelte files:
 
 ``
